debug: false
server: 
   address: 0.0.0.0
   port: 9998
spring:
   kafka:
     consumer:
        bootstrap-servers: 10.0.2.151:9092
        group-id: testA
        auto-offset-reset: latest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        enable-auto-commit: true
        auto-commit-interval: 1000
        properties:
          spring:
            json:
              trusted:
                packages: com.charida.kafka.json
     producer:
        bootstrap-servers: 10.0.2.151:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
custom:
   hadoop:
      core: file:///usr/hadoop-3.1.2/etc/hadoop/core-site.xml
      hdfs: file:///usr/hadoop-3.1.2/etc/hadoop/hdfs-site.xml
   upload:
      dir: analytics