debug: false
server: 
   address: 0.0.0.0
   port: 9999
spring:
   kafka:
     consumer:
        bootstrap-servers: 10.0.2.151:9092
        group-id: testA
        auto-offset-reset: latest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        enable-auto-commit: true
        auto-commit-interval: 1000
     producer:
        bootstrap-servers: 10.0.2.151:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
   topic:
      predict: test-test
